[package]
name = "server"
version = "0.1.0"
authors = ["Jalol Rahimov <jalolrahimov@gmail.com>"]
edition = "2019"

[dependencies]
clap = "2"

protector = { path = "./protector" }
thread_pool = { path = "./thread_pool" }
